######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 6 13:19:50 2010
######################################################################
# To use with Mac OSX, and generate a plain old make file, run:
# qmake -spec macx-g++

TEMPLATE = app
TARGET = lstune
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug_and_release
# LIBS += 
# Qt 5 uses the 'widgets' module; Qt 4 includes everything in 'gui'.
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Need to include this for Qt 4.6. This was pulled into qt moblity for 4.7
exists($$[QT_INSTALL_HEADERS]/QtMultimedia) {
   QT += multimedia
} else {
   # For qt mobility, qt 4.7
   CONFIG += mobility
   MOBILITY = multimedia
}

FORMS       = tunerForm.ui

win32 {
  DEFINES += BUILD_LINUX=0 BUILD_WIN32=1 BUILD_MACX=0
  RC_FILE = ../misc/lstune.rc
  debug {
    CONFIG += console
  }
}
unix {
  DEFINES += BUILD_LINUX=1 BUILD_WIN32=0 BUILD_MACX=0
}
macx {
  DEFINES += BUILD_LINUX=0 BUILD_WIN32=0 BUILD_MACX=1
  ICON = ../misc/fish.icns

  # ---------------------------------------------------------------------------
  # PowerPC / Intel universal-binary settings.
  # Requires: Xcode 3.1.x, Qt 4.6-4.8 Carbon, MacOSX10.4u SDK.
  # This produces a fat binary that runs on both G4 and G5 (generic baseline;
  # no -mcpu=970 or -mpowerpc64 flags are set here).
  # ---------------------------------------------------------------------------
  CONFIG += ppc
  QMAKE_MAC_SDK = /Developer/SDKs/MacOSX10.4u.sdk
  QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.4
}

# Input
HEADERS += sound.h wheel.h notes.h filter.h tuner.h noteGuesser.h AudioIO.h LED.h
SOURCES += main.cc sound.cc wheel.cc notes.cc filter.cc tuner.cc noteGuesser.cc AudioIO.cc LED.cc

